version: '3.4'
# ~~> DEFININDO OS VOLUMES
volumes:
  mongo_data:

# ~~> DEFININDO CONTAINER DO POSTGRES
services:
  discountdb:
    container_name: discountdb
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD==admin1234
    - POSTGRES_DB=DiscountDb
    - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    image: postgres
    ports:
       - "5432:5432" 
    
  pgadmin:
    container_name: pgadmin
    environment:
       - PGADMIN_DEFAULT_EMAIL=admin@macoratti.com
       - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    image: dpage/pgadmin4
    ports:
       - "5050:80" 
   
# ~~> DEFININDO CONTAINER DA DISCOUNT.API
  discount.api:
    container_name: discount.api
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    image: discountapi
    build:
      context: .
      dockerfile: Api.Discount/Dockerfile
    depends_on:
       - discountdb
    ports:
       - "8002:80"